# Generated by Django 4.0.5 on 2022-06-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0002_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconcilicationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата сверки')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconciliation_app.product', verbose_name='товар')),
            ],
        ),
    ]
