# Generated by Django 4.0.5 on 2022-06-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0004_alter_reconcilicationdate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='дата сверки')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconciliation_app.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'дата сверки',
                'verbose_name_plural': 'даты сверки',
                'ordering': ['product'],
            },
        ),
        migrations.DeleteModel(
            name='ReconcilicationDate',
        ),
    ]
