# Generated by Django 4.0.5 on 2022-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0006_alter_reconciliationdate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationdate',
            name='date',
            field=models.DateField(blank=True, verbose_name='дата сверки'),
        ),
    ]
