# Generated by Django 4.0.5 on 2022-06-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0007_alter_reconciliationdate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconciliation_app.productcategory', verbose_name='категория товара'),
        ),
    ]
